DROP DATABASE IF EXISTS gameme;

CREATE DATABASE gameme;

USE gameme

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL,
    time VARCHAR(20) NOT NULL,
     KEY (id)
)

